# Generated by Django 6.0.2 on 2026-02-17 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profille',
        ),
    ]
